/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PickupManager {
  export type PickupStruct = {
    pickupId: string;
    user: AddressLike;
    courier: AddressLike;
    status: BigNumberish;
    material: string;
    weightKg: BigNumberish;
    createdAt: BigNumberish;
    assignedAt: BigNumberish;
    completedAt: BigNumberish;
  };

  export type PickupStructOutput = [
    pickupId: string,
    user: string,
    courier: string,
    status: bigint,
    material: string,
    weightKg: bigint,
    createdAt: bigint,
    assignedAt: bigint,
    completedAt: bigint
  ] & {
    pickupId: string;
    user: string;
    courier: string;
    status: bigint;
    material: string;
    weightKg: bigint;
    createdAt: bigint;
    assignedAt: bigint;
    completedAt: bigint;
  };
}

export interface PickupManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptPickup"
      | "assignRole"
      | "completePickup"
      | "courierActivePickups"
      | "createPickup"
      | "getPickup"
      | "getPickupByIndex"
      | "getPickupCount"
      | "getRole"
      | "owner"
      | "pickupIds"
      | "pickups"
      | "renounceOwnership"
      | "transferOwnership"
      | "userRoles"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PickupAssigned"
      | "PickupCompleted"
      | "PickupCreated"
      | "RoleAssigned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptPickup",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "assignRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completePickup",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "courierActivePickups",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPickup",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPickup", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getPickupByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPickupCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pickupIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pickups", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRoles",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptPickup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assignRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completePickup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courierActivePickups",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPickup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPickup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPickupByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPickupCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pickupIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pickups", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userRoles", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PickupAssignedEvent {
  export type InputTuple = [
    pickupIdHash: BytesLike,
    pickupId: string,
    courier: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    pickupIdHash: string,
    pickupId: string,
    courier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    pickupIdHash: string;
    pickupId: string;
    courier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PickupCompletedEvent {
  export type InputTuple = [
    pickupIdHash: BytesLike,
    pickupId: string,
    courier: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    pickupIdHash: string,
    pickupId: string,
    courier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    pickupIdHash: string;
    pickupId: string;
    courier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PickupCreatedEvent {
  export type InputTuple = [
    pickupIdHash: BytesLike,
    pickupId: string,
    user: AddressLike,
    material: string,
    weightKg: BigNumberish
  ];
  export type OutputTuple = [
    pickupIdHash: string,
    pickupId: string,
    user: string,
    material: string,
    weightKg: bigint
  ];
  export interface OutputObject {
    pickupIdHash: string;
    pickupId: string;
    user: string;
    material: string;
    weightKg: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAssignedEvent {
  export type InputTuple = [user: AddressLike, role: BigNumberish];
  export type OutputTuple = [user: string, role: bigint];
  export interface OutputObject {
    user: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PickupManager extends BaseContract {
  connect(runner?: ContractRunner | null): PickupManager;
  waitForDeployment(): Promise<this>;

  interface: PickupManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptPickup: TypedContractMethod<[pickupId: string], [void], "nonpayable">;

  assignRole: TypedContractMethod<
    [user: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  completePickup: TypedContractMethod<[pickupId: string], [void], "nonpayable">;

  courierActivePickups: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  createPickup: TypedContractMethod<
    [pickupId: string, material: string, weightKg: BigNumberish],
    [string],
    "nonpayable"
  >;

  getPickup: TypedContractMethod<
    [pickupId: string],
    [PickupManager.PickupStructOutput],
    "view"
  >;

  getPickupByIndex: TypedContractMethod<
    [index: BigNumberish],
    [PickupManager.PickupStructOutput],
    "view"
  >;

  getPickupCount: TypedContractMethod<[], [bigint], "view">;

  getRole: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pickupIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  pickups: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        pickupId: string;
        user: string;
        courier: string;
        status: bigint;
        material: string;
        weightKg: bigint;
        createdAt: bigint;
        assignedAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userRoles: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptPickup"
  ): TypedContractMethod<[pickupId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignRole"
  ): TypedContractMethod<
    [user: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completePickup"
  ): TypedContractMethod<[pickupId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "courierActivePickups"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPickup"
  ): TypedContractMethod<
    [pickupId: string, material: string, weightKg: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPickup"
  ): TypedContractMethod<
    [pickupId: string],
    [PickupManager.PickupStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPickupByIndex"
  ): TypedContractMethod<
    [index: BigNumberish],
    [PickupManager.PickupStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPickupCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRole"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pickupIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "pickups"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        pickupId: string;
        user: string;
        courier: string;
        status: bigint;
        material: string;
        weightKg: bigint;
        createdAt: bigint;
        assignedAt: bigint;
        completedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userRoles"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PickupAssigned"
  ): TypedContractEvent<
    PickupAssignedEvent.InputTuple,
    PickupAssignedEvent.OutputTuple,
    PickupAssignedEvent.OutputObject
  >;
  getEvent(
    key: "PickupCompleted"
  ): TypedContractEvent<
    PickupCompletedEvent.InputTuple,
    PickupCompletedEvent.OutputTuple,
    PickupCompletedEvent.OutputObject
  >;
  getEvent(
    key: "PickupCreated"
  ): TypedContractEvent<
    PickupCreatedEvent.InputTuple,
    PickupCreatedEvent.OutputTuple,
    PickupCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAssigned"
  ): TypedContractEvent<
    RoleAssignedEvent.InputTuple,
    RoleAssignedEvent.OutputTuple,
    RoleAssignedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PickupAssigned(bytes32,string,address,uint256)": TypedContractEvent<
      PickupAssignedEvent.InputTuple,
      PickupAssignedEvent.OutputTuple,
      PickupAssignedEvent.OutputObject
    >;
    PickupAssigned: TypedContractEvent<
      PickupAssignedEvent.InputTuple,
      PickupAssignedEvent.OutputTuple,
      PickupAssignedEvent.OutputObject
    >;

    "PickupCompleted(bytes32,string,address,uint256)": TypedContractEvent<
      PickupCompletedEvent.InputTuple,
      PickupCompletedEvent.OutputTuple,
      PickupCompletedEvent.OutputObject
    >;
    PickupCompleted: TypedContractEvent<
      PickupCompletedEvent.InputTuple,
      PickupCompletedEvent.OutputTuple,
      PickupCompletedEvent.OutputObject
    >;

    "PickupCreated(bytes32,string,address,string,uint256)": TypedContractEvent<
      PickupCreatedEvent.InputTuple,
      PickupCreatedEvent.OutputTuple,
      PickupCreatedEvent.OutputObject
    >;
    PickupCreated: TypedContractEvent<
      PickupCreatedEvent.InputTuple,
      PickupCreatedEvent.OutputTuple,
      PickupCreatedEvent.OutputObject
    >;

    "RoleAssigned(address,uint8)": TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;
    RoleAssigned: TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;
  };
}
